import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Deployment Test{" "}
          <a
            target="_blank"
            rel="noreferrer noopener"
            href="https://nextjs.org"
          >
            Next.js
          </a>{" "}
          on{" "}
          <a
            target="_blank"
            rel="noreferrer noopener"
            href="https://vercel.com"
          >
            Vercel
          </a>
        </h1>
      </main>
    </div>
  );
};

export default Home;
